### ISSUE TITLE
Very slow sync with addindex and txindex

### ISSUE THREAD

**Issue by romainPellerin** [btcsuite/btcd#1299] opened 2018-09-18 21:25 UTC
Hi,

we are running a BTCD node with **addrindex=1** and **txindex=1**.

Our node processes 1 block every 7s in average and at this rhythm we will need more than 12 days to sync-up the BTC blockchain.

`2018-09-18 21:09:05.195 [INF] SYNC: Processed 1 block in the last 12.93s (1965 transactions, height 388874, 2015-12-17 12:58:45 +0000 UTC)
2018-09-18 21:09:18.286 [INF] SYNC: Processed 1 block in the last 13.09s (2574 transactions, height 388875, 2015-12-17 13:13:34 +0000 UTC)
2018-09-18 21:09:29.880 [INF] SYNC: Processed 2 blocks in the last 11.59s (1994 transactions, height 388877, 2015-12-17 13:24:59 +0000 UTC)
2018-09-18 21:09:40.588 [INF] SYNC: Processed 1 block in the last 10.7s (1682 transactions, height 388878, 2015-12-17 13:33:15 +0000 UTC)
2018-09-18 21:10:00.588 [INF] SYNC: Processed 2 blocks in the last 19.99s (4106 transactions, height 388880, 2015-12-17 14:03:18 +0000 UTC)
2018-09-18 21:10:12.584 [INF] SYNC: Processed 1 block in the last 11.99s (1106 transactions, height 388881, 2015-12-17 14:04:50 +0000 UTC)
2018-09-18 21:10:26.171 [INF] SYNC: Processed 1 block in the last 13.58s (1274 transactions, height 388882, 2015-12-17 14:05:53 +0000 UTC)
2018-09-18 21:10:44.465 [INF] SYNC: Processed 1 block in the last 18.29s (671 transactions, height 388883, 2015-12-17 14:10:43 +0000 UTC)
2018-09-18 21:10:57.952 [INF] SYNC: Processed 2 blocks in the last 13.48s (1522 transactions, height 388885, 2015-12-17 14:17:23 +0000 UTC)
2018-09-18 21:11:17.168 [INF] SYNC: Processed 2 blocks in the last 19.21s (2421 transactions, height 388887, 2015-12-17 14:29:41 +0000 UTC)
2018-09-18 21:11:32.258 [INF] SYNC: Processed 1 block in the last 15.09s (3119 transactions, height 388888, 2015-12-17 14:57:35 +0000 UTC)
2018-09-18 21:11:47.048 [INF] SYNC: Processed 1 block in the last 14.78s (1625 transactions, height 388889, 2015-12-17 15:00:43 +0000 UTC)
2018-09-18 21:11:57.248 [INF] SYNC: Processed 2 blocks in the last 10.19s (1952 transactions, height 388891, 2015-12-17 15:05:32 +0000 UTC)
2018-09-18 21:12:14.175 [INF] SYNC: Processed 2 blocks in the last 16.92s (2209 transactions, height 388893, 2015-12-17 15:16:54 +0000 UTC)
2018-09-18 21:12:28.464 [INF] SYNC: Processed 2 blocks in the last 14.28s (3207 transactions, height 388895, 2015-12-17 15:43:40 +0000 UTC)
2018-09-18 21:12:41.956 [INF] SYNC: Processed 1 block in the last 13.49s (2348 transactions, height 388896, 2015-12-17 15:54:40 +0000 UTC)
2018-09-18 21:12:55.690 [INF] SYNC: Processed 1 block in the last 13.73s (2630 transactions, height 388897, 2015-12-17 16:09:52 +0000 UTC)
2018-09-18 21:13:10.591 [INF] SYNC: Processed 1 block in the last 14.9s (3189 transactions, height 388898, 2015-12-17 16:41:44 +0000 UTC)
2018-09-18 21:13:24.159 [INF] SYNC: Processed 1 block in the last 13.56s (1798 transactions, height 388899, 2015-12-17 16:42:52 +0000 UTC)
2018-09-18 21:13:36.647 [INF] SYNC: Processed 1 block in the last 12.48s (1668 transactions, height 388900, 2015-12-17 16:56:45 +0000 UTC)
2018-09-18 21:13:50.851 [INF] SYNC: Processed 1 block in the last 14.2s (2242 transactions, height 388901, 2015-12-17 17:07:30 +0000 UTC)
2018-09-18 21:13:50.974 [INF] SYNC: Lost peer 134.3.26.190:8333 (outbound)
2018-09-18 21:13:50.975 [INF] SYNC: Syncing to block height 541985 from peer 198.48.234.73:8333
2018-09-18 21:13:50.976 [WRN] SYNC: Received block message from unknown peer 134.3.26.190:8333 (outbound)
2018-09-18 21:14:02.861 [INF] SYNC: Processed 1 block in the last 12s (1097 transactions, height 388902, 2015-12-17 17:12:51 +0000 UTC)
2018-09-18 21:14:15.962 [INF] SYNC: Processed 1 block in the last 13.1s (1280 transactions, height 388903, 2015-12-17 17:18:14 +0000 UTC)
2018-09-18 21:14:29.172 [INF] SYNC: Processed 1 block in the last 13.21s (1741 transactions, height 388904, 2015-12-17 17:29:09 +0000 UTC)
2018-09-18 21:14:29.173 [INF] SYNC: New valid peer 139.196.8.136:8333 (outbound) (/Satoshi:0.13.2/)
2018-09-18 21:14:47.749 [INF] SYNC: Processed 2 blocks in the last 18.57s (1668 transactions, height 388906, 2015-12-17 17:35:13 +0000 UTC)
2018-09-18 21:15:01.764 [INF] SYNC: Processed 1 block in the last 14.01s (788 transactions, height 388907, 2015-12-17 17:40:50 +0000 UTC)
2018-09-18 21:15:11.896 [INF] SYNC: Processed 2 blocks in the last 10.13s (1326 transactions, height 388909, 2015-12-17 17:50:23 +0000 UTC)`

We are running this node on a m5.large instance on AWS (2 vCPU | 8Go RAM | EBS-Only | Bandwith Up to 3,500 Mbps) and here is the top command result:
`21716 x     5 -15 1430376 519964  12272 S  **90.3**  **6.6** 125:03.43 btcd`

What would you recommend for us to accelerate the sync and be able to use our updated node asap?

**Comment by Roasbeef** [comment] 2018-10-13 00:36
IF you're using networked attached storage, then that can slow things down quite a bit. The primary bottleneck when using the addrindex is that it needs to construct the entire UTXO set (if you're running an older versions) from the PoV of that block in order to be able to reference which outputs are being spent. Beyond that the primary bottle necks are a lack of parallel block download, and also a lack of a UTXO index.

**Comment by trungthanhnt** [comment] 2019-05-01 03:11
Mine is much more slower.
2019-05-01 10:07:45.915 [INF] INDX: Indexed 1 block in the last 40.43s (1910 transactions, height 489508, 2017-10-12 19:25:11 +0700 +07)
2019-05-01 10:08:37.428 [INF] INDX: Indexed 1 block in the last 51.51s (1948 transactions, height 489509, 2017-10-12 19:28:41 +0700 +07)
2019-05-01 10:10:01.713 [INF] INDX: Indexed 1 block in the last 1m24.28s (2333 transactions, height 489510, 2017-10-12 19:42:37 +0700 +07)
2019-05-01 10:10:17.272 [INF] INDX: Indexed 1 block in the last 15.55s (468 transactions, height 489511, 2017-10-12 19:47:19 +0700 +07)
2019-05-01 10:11:12.799 [INF] INDX: Indexed 1 block in the last 55.52s (1822 transactions, height 489512, 2017-10-12 19:47:38 +0700 +07)

**Comment by l0k1verloren** [comment] 2019-11-26 15:39
Because of how slow the sync is, I tested it without those indexes enabled (on a fast samsung EVO SSD). It made absolutely no noticable difference, maybe a tiny bit faster but I don't think the indices are the cause of the slow performance. In any case you have to have them on to use the wallet with it anyhow and it can't be made to reindex it currently, as far as I know. 

The back end database is definitely where the problem is. Some mixture of synchronisation, lack of opportunistic parallelization and excessive allocation of new variables. Profiling shows that between short bursts of full CPU thread saturation of about 20% of the time with snakey chains of single thread Validate() function running in between. The script execution engine probably has some issues in it also.

By the way, I have rarely seen it pass 2000tx/s in validation, even with the seed on the same machine connected over loopback. If a block had 2000tx's in it, it would take at least a second to validate it. It is definitely a major part of the bottleneck.

**Comment by jakesyl** [comment] 2020-03-09 19:09
Closing in favor of #1339, there's been far more discussion there and this is a duplicate

**Closed by jakesyl** 2020-03-09 19:09 UTC
Labels: duplicate
