### ISSUE TITLE
go install hangs on btcec, cannot build

### ISSUE THREAD

**Issue by carryforward** [btcsuite/btcd#277] opened 2015-02-06 03:44 UTC
I am installing btcd and btcwallet after erasing my go/src directory. it seems to peg the processor for >5 minutes while building github.com/btcsuite/btcec  it complains about signal killed.

#### BTCD
```
factom@factom-VirtualBox:~$ go get -v github.com/btcsuite/btcd/...
github.com/btcsuite/btcd (download)
github.com/btcsuite/fastsha256 (download)
github.com/btcsuite/btclog (download)
github.com/btcsuite/seelog (download)
github.com/btcsuite/btcutil (download)
github.com/btcsuite/btcec (download)
github.com/btcsuite/btcnet (download)
Fetching https://golang.org/x/crypto/ripemd160?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ripemd160?go-get=1 (status code 200)
get "golang.org/x/crypto/ripemd160": found meta tag main.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ripemd160?go-get=1
get "golang.org/x/crypto/ripemd160": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
github.com/btcsuite/goleveldb (download)
code.google.com/p/snappy-go (download)
github.com/btcsuite/btcjson (download)
github.com/btcsuite/btcws (download)
github.com/btcsuite/go-flags (download)
github.com/btcsuite/go-socks (download)
github.com/btcsuite/websocket (download)
github.com/davecgh/go-spew (download)
github.com/btcsuite/fastsha256
github.com/btcsuite/btcd/wire
github.com/btcsuite/seelog
github.com/btcsuite/btclog
github.com/btcsuite/btcd/addrmgr
github.com/btcsuite/btcec
go build github.com/btcsuite/btcec: signal: killed
github.com/btcsuite/btcnet
github.com/btcsuite/btcutil/base58
golang.org/x/crypto/ripemd160
github.com/btcsuite/goleveldb/leveldb/util
github.com/btcsuite/goleveldb/leveldb/cache
github.com/btcsuite/goleveldb/leveldb/comparer
github.com/btcsuite/goleveldb/leveldb/storage
github.com/btcsuite/goleveldb/leveldb/errors
github.com/btcsuite/goleveldb/leveldb/filter
github.com/btcsuite/goleveldb/leveldb/iterator
github.com/btcsuite/goleveldb/leveldb/journal
github.com/btcsuite/goleveldb/leveldb/memdb
github.com/btcsuite/goleveldb/leveldb/opt
code.google.com/p/snappy-go/snappy
github.com/btcsuite/goleveldb/leveldb/table
github.com/btcsuite/goleveldb/leveldb
github.com/btcsuite/btcd/limits
github.com/btcsuite/btcjson
github.com/btcsuite/btcws
github.com/btcsuite/go-flags
github.com/btcsuite/go-socks/socks
github.com/btcsuite/websocket
github.com/davecgh/go-spew/spew
github.com/btcsuite/btcd/database/ldb/dbtest
factom@factom-VirtualBox:~$ 

```

#### BTCWALLET
```
factom@factom-VirtualBox:~$ go get -v github.com/btcsuite/btcwallet/...
github.com/btcsuite/btcwallet (download)
github.com/btcsuite/btcrpcclient (download)
github.com/btcsuite/bolt (download)
github.com/btcsuite/btcec
go build github.com/btcsuite/btcec: signal: killed
github.com/btcsuite/btcwallet/rename
golang.org/x/crypto/poly1305
golang.org/x/crypto/salsa20/salsa
golang.org/x/crypto/nacl/secretbox
golang.org/x/crypto/pbkdf2
golang.org/x/crypto/scrypt
github.com/btcsuite/btcwallet/snacl
github.com/btcsuite/btcwallet/walletdb
github.com/btcsuite/bolt
github.com/btcsuite/btcwallet/walletdb/bdb
factom@factom-VirtualBox:~$ 
```

btcd and btcwallet fails to build.

**Comment by jrick** [comment] 2015-02-06 04:49
Try using `go get` with the `-u` flag to update code.  There was a change committed to btcec which makes it use much less memory when compiling.  You likely have the old code and your OS is killing the process for using too much memory.

**Comment by davecgh** [comment] 2015-02-06 07:18
As a point of reference, mine is building without any issues.  I pointed my `GOPATH` to a temp location so it would pull all of the code fresh:
```
$ export GOPATH=~/tmpgo; go get -v github.com/btcsuite/btcd/...
github.com/btcsuite/btcd (download)
github.com/btcsuite/fastsha256 (download)
...
github.com/btcsuite/btcec (download)
...
github.com/btcsuite/fastsha256
github.com/btcsuite/seelog
github.com/btcsuite/btcec
github.com/btcsuite/btcutil/base58
...
$ export PATH=$PATH:$GOPATH; which btcd
/home/davec/tmpgo/bin/btcd
```

**Comment by davecgh** [comment] 2015-02-06 08:08
Also, can you try to build it manually?

```
$ cd $GOPATH/src/github.com/btcsuite/btcec
$ go build
(if successful)
$ go test
```

**Comment by davecgh** [comment] 2015-02-06 17:40
The merging of the btcec repo into btcd as discussed in #214 has been completed, so my above commands with the latest code should be changed to the following:

```
$ cd $GOPATH/src/github.com/btcsuite/btcd/btcec
$ go build
(if successful)
$ go test
```

**Comment by carryforward** [comment] 2015-02-06 18:12
ok, I can confirm this is a memory issue.  I was testing on a vm (different underlying computer than my last vm issue).  I switched to the bare metal computer.  I set a new goroot directory as suggested.  

I ran go get -v github.com/btcsuite/btcd/...  at 11:55 central time, after the btcec change was pushed ( I think).  

it ran fine, while it built the first few includes.  the system was using ~500 MB ram.  When it got to btcec the system jumped quickly to use the full 3GB dram.  it then proceeded to take another 1.5 GB of swap space.  On the bare metal machine with access to 4GB memory extra to compile it did successfully build.  My VM didn't have access to 4GB of memory, and couldn't build it.

**Comment by jrick** [comment] 2015-02-06 18:31
What Go version, and what is the host OS and arch?

**Comment by davecgh** [comment] 2015-02-06 18:34
Thanks for the update.  The high memory usage needed by btcec was fixed in commit 9535058a7bcb8965f9293609af0c9d3aed4aad7f, so I'm curious if it's using the old code somehow.

**Comment by carryforward** [comment] 2015-02-06 21:34
two bate metal machines have this problem.
Machine1: desktop running xubuntu amd64 bit 14.04 
go version "go version go1.2.1 linux/amd64"
8 year old computer with early generation 64bit amd processor

Machine2: laptop xubuntu core2 64bit processor xubuntu 14.04
go version "go version go1.2.1 linux/amd64"
no swap space allocated, 3.8GB ram available.

machine1 eventually builds, due to swap space.  machine 2 fails after quickly maxing out ram.

I used the temp go directory and go get -v as you described to get these results.

**Comment by davecgh** [comment] 2015-02-06 21:51
Ah, that would be why.  Go 1.2.1 isn't supported any more.  I'd start by updating to Go 1.4.1.

In addition to solving your issue, it has a lot of optimizations to help btcd (and friends) run faster such as precise GC.

**Comment by davecgh** [comment] 2015-02-06 22:35
Alright, so I have confirmed that I hit this with Go version 1.2.1, but not with Go 1.3.3 or 1.4.1.  I'm going to close this since Go 1.2.1 is no longer supported and the problem does not exist with the supported versions of Go 1.3.3 or 1.4.1.

For reference, here are the following peak memory usages I saw when pulling and building everything from scratch (compile time):
```
Go 1.2.1 - 2959MB (2.89GB)
Go 1.3.3 - 216MB
Go 1.4.1 - 244MB
```

**Closed by davecgh** 2015-02-06 22:35 UTC

**Comment by carryforward** [comment] 2015-02-07 02:26
Thanks for putting so much effort into this when it turned out to be innocuous.  This is a bit dissapointing, since the canical repositories for the LTS version of ubuntu look to be frozen at 1.2.1.  No more one line installing of golang. :(
