### ISSUE TITLE
--addrindex doesn't work on preprocessed blocks

### ISSUE THREAD

**Issue by manan19** [btcsuite/btcd#303] opened 2015-02-17 19:45 UTC
Generating address index with --addrindex option succeeds when processing blocks from scratch.

But generating the address index on a fully synced node throws the following errors -
```
11:40:46 2015-02-17 [ERR] ADXR: Couldn't get referenced txOut (cf2ab4e635099dfc8f2c0438c2d7eb6fdbc57ce3c7d497869e1466f03f872d61:0): <nil>
```

To reproduce bug, drop the address index from a fully synced node and then try to rengenerate.

```
$ btcd --testnet --dropaddrindex --rpclisten=127.0.0.1:18334 --listen=127.0.0.1:18555
11:38:37 2015-02-17 [INF] BTCD: Version 0.9.0-beta
11:38:37 2015-02-17 [INF] BTCD: Loading block database from '/Users/manan/Library/Application Support/Btcd/data/testnet/blocks_leveldb'
11:38:37 2015-02-17 [INF] BTCD: Block database loaded with block height 323335
11:38:37 2015-02-17 [INF] BTCD: Deleting entire addrindex.
11:39:12 2015-02-17 [INF] BTCD: Successfully deleted addrindex, exiting

$ btcd --testnet --addrindex --rpclisten=127.0.0.1:18334 --listen=127.0.0.1:18555
11:40:32 2015-02-17 [INF] BTCD: Version 0.9.0-beta
11:40:32 2015-02-17 [INF] BTCD: Loading block database from '/Users/manan/Library/Application Support/Btcd/data/testnet/blocks_leveldb'
11:40:32 2015-02-17 [INF] BTCD: Block database loaded with block height 323335
11:40:32 2015-02-17 [WRN] AMGR: Skipping bound address: address 127.0.0.1 is not routable
11:40:32 2015-02-17 [INF] BMGR: Generating initial block node index.  This may take a while...
11:40:33 2015-02-17 [INF] BMGR: Block index generation complete
11:40:33 2015-02-17 [INF] SRVR: Server listening on 127.0.0.1:18555
11:40:33 2015-02-17 [INF] ADXR: Building up address index from height 0 to 323335.
11:40:33 2015-02-17 [INF] RPCS: RPC server listening on 127.0.0.1:18334
11:40:33 2015-02-17 [INF] AMGR: Loaded 1742 addresses from file '/Users/manan/Library/Application Support/Btcd/data/testnet/peers.json'
11:40:33 2015-02-17 [INF] DISC: 6 addresses found from DNS seed testnet-seed.bitcoin.petertodd.org
11:40:33 2015-02-17 [INF] DISC: 1 addresses found from DNS seed testnet-seed.bluematt.me
11:40:34 2015-02-17 [INF] DISC: 41 addresses found from DNS seed testnet-seed.bitcoin.schildbach.de
11:40:43 2015-02-17 [INF] ADXR: Indexed addresses of 20539 blocks in the last 10s (31844 transactions, height 20538, 2012-08-18 16:34:20 -0700 PDT)
11:40:43 2015-02-17 [INF] BMGR: New valid peer 78.46.18.137:18333 (outbound) (/Satoshi:0.8.3/)
11:40:43 2015-02-17 [INF] BMGR: Syncing to block height 323335 from peer 78.46.18.137:18333
11:40:46 2015-02-17 [ERR] ADXR: Couldn't get referenced txOut (cf2ab4e635099dfc8f2c0438c2d7eb6fdbc57ce3c7d497869e1466f03f872d61:0): <nil>
11:40:46 2015-02-17 [ERR] ADXR: Couldn't get referenced txOut (cf2ab4e635099dfc8f2c0438c2d7eb6fdbc57ce3c7d497869e1466f03f872d61:1): <nil>
11:40:48 2015-02-17 [ERR] ADXR: Couldn't get referenced txOut (32638ada91a0d21a4236ceb824a32bc18736c5cd8b466222ac822c359db22d61:0): <nil>
11:40:49 2015-02-17 [ERR] ADXR: Couldn't get referenced txOut (32638ada91a0d21a4236ceb824a32bc18736c5cd8b466222ac822c359db22d61:1): <nil>
11:40:53 2015-02-17 [INF] ADXR: Indexed addresses of 37753 blocks in the last 10.23s (65137 transactions, height 58291, 2013-03-13 00:38:29 -0700 PDT)
11:40:53 2015-02-17 [INF] BMGR: New valid peer 54.210.107.2:18333 (outbound) (/Satoshi:0.9.2.1/)
11:41:02 2015-02-17 [ERR] ADXR: Couldn't get referenced txOut (58e04fb6fd999ec59ce4b6d3716affb37967028b990883c7bd70a4e9b6392d61:0): <nil>
11:41:02 2015-02-17 [ERR] ADXR: Couldn't get referenced txOut (58e04fb6fd999ec59ce4b6d3716affb37967028b990883c7bd70a4e9b6392d61:1): <nil>
11:41:03 2015-02-17 [INF] DISC: DNS discovery failed on seed testnet-seed.alexykot.me: lookup testnet-seed.alexykot.me: no such host
11:41:03 2015-02-17 [INF] ADXR: Indexed addresses of 8335 blocks in the last 10s (52082 transactions, height 66626, 2013-04-14 12:19:30 -0700 PDT)
11:41:03 2015-02-17 [INF] BMGR: New valid peer 54.237.211.7:18333 (outbound) (/Satoshi:0.9.1/)

```

**Comment by Roasbeef** [comment] 2015-02-17 19:56
Using the `getrawtransaction` RPC, are you able to successfully query for that particular `txid`?

**Comment by jrick** [comment] 2015-02-17 19:58
By that error message, this looks like a non-nil interface to a nil concrete type.

**Comment by manan19** [comment] 2015-02-17 20:11
@Roasbeef No.

```
$ btcctl --rpcserver=localhost:18334 getrawtransaction cf2ab4e635099dfc8f2c0438c2d7eb6fdbc57ce3c7d497869e1466f03f872d61 --notls
rpcCommand: -5: No information available about transaction

$ btcctl --rpcserver=localhost:18334 getrawtransaction 32638ada91a0d21a4236ceb824a32bc18736c5cd8b466222ac822c359db22d61 --notls
rpcCommand: -5: No information available about transaction
```

**Comment by Roasbeef** [comment] 2015-02-17 20:18
@manan19 looks like a case of block corruption caused by `goleveldb`, similar to: #199. For now, you'll have to nuke your DB and start over with a fresh sync. In the near future we'll be moving away from storing blocks within `leveldb`. We'll instead store block as flat files which should significantly increase performance, and avoid errors like this tied to the implementation of `goleveldb`

Also the logging error message here isn't as clear as it should be. It currently couples an error returned by the `db` during lookup, with an alternate case of `db` not finding anything for the particular query. I'll have a patch soon to separate the cases into distinct error messages, which should help with future debugging.

**Comment by davecgh** [comment] 2015-02-24 19:28
Closing this as the issue is what @Roasbeef described.

**Closed by davecgh** 2015-02-24 19:28 UTC
