### ISSUE TITLE
btcd sync keeps freezing

### ISSUE THREAD

**Issue by nutmix** [btcsuite/btcd#1136] opened 2018-03-03 19:37 UTC
It runs for about 1 hour, then dies.  I see this because a) the cpu usage drops from 180% to 1%, and when I poll the server on https://bitnodes.earn.com the height stays the same (and the % goes down).

We have been trying to sycn the blockchain since a week.  It runs for an hour or two then stops syncing.  The process is still running.

When it stops syncing, the logs fill up with stuff like this:

2018-03-03 19:30:17.509 [INF] SYNC: New valid peer 52.54.198.224:8333 (outbound) (/Satoshi:0.16.0/)
2018-03-03 19:30:26.116 [INF] SYNC: New valid peer 62.183.116.182:22567 (inbound) (/Satoshi:0.15.0/)
2018-03-03 19:31:23.173 [INF] SYNC: Lost peer 62.183.116.182:22567 (inbound)
2018-03-03 19:32:23.587 [INF] SYNC: New valid peer 46.101.246.115:47819 (inbound) (/Snoopy:0.2.1/)
2018-03-03 19:32:23.748 [ERR] PEER: Can't read message from 46.101.246.115:47819 (inbound): read tcp4 45.33.44.212:8333->46.101.246.115:47819: read: connection reset by peer
2018-03-03 19:32:23.748 [INF] SYNC: Lost peer 46.101.246.115:47819 (inbound)
2018-03-03 19:32:26.108 [INF] SYNC: New valid peer 128.235.40.191:12835 (inbound) (/btc.cs.njit.edu:0.1/)
2018-03-03 19:32:27.421 [INF] SYNC: Lost peer 128.235.40.191:12835 (inbound)
2018-03-03 19:32:48.002 [INF] SYNC: New valid peer 18.196.84.227:49734 (inbound) (/bitcoin-seeder:0.01/)
2018-03-03 19:32:49.148 [INF] SYNC: Lost peer 18.196.84.227:49734 (inbound)

The only solution is to restart the btcd process every couple of hours, but we can only do this when we are online.  It is going to take months at this rate.

The server is a linode ubuntu 16 LTS with 4 GB ram, dual core, and 300GB secondary volume for data.

we tried disabling the listener, but this did not help

**Comment by pankajagarwal** [comment] 2018-03-04 06:35
i'm running into the very same issue. I am using the master branch in case that's not the stable branch.

**Comment by pankajagarwal** [comment] 2018-03-04 07:39
seems like it's a duplicate of #1099 and #1024

**Comment by qshuai** [comment] 2018-03-24 05:49
export $GOBIN path to your PATH

**Comment by simernes** [comment] 2018-05-22 09:50
Same issue here. Built from source yesterday. On Ubuntu 18.04 64 bit

**Comment by qshuai** [comment] 2018-05-23 02:51
Same issue

**Comment by rubenkr** [comment] 2018-06-15 18:48
Same Same here

**Comment by judezhu** [comment] 2018-12-31 01:18
same here

**Closed** 2019-04-27 00:42 UTC
