### ISSUE TITLE
RPCS: Failed to marshal reply: rpcversion '' is invalid

### ISSUE THREAD

**Issue by regata** [btcsuite/btcd#1711] opened 2021-04-16 16:32 UTC
Seeing this error when calling `getinfo` using https://github.com/petertodd/python-bitcoinlib:

```
RPCS: Failed to marshal reply: rpcversion '' is invalid
```

I'm using the master@2d7825c. I believe it happens because btcd expects `jsonrpc` field to be provided

https://github.com/btcsuite/btcd/blob/2d7825cf709fc6ac15921cecfd4d62ec78ccbba2/btcjson/jsonrpc.go#L96-L101

when processing RPC requests:

https://github.com/btcsuite/btcd/blob/2d7825cf709fc6ac15921cecfd4d62ec78ccbba2/rpcserver.go#L4152-L4155

However, bitcoinlib does not send it
https://github.com/petertodd/python-bitcoinlib/blob/0ea83c4fd499c63823754627c69ebdd79dc0d62c/bitcoin/rpc.py#L217-L220

What is the "ground truth" for the rpc spec? is the field expected to be set by clients?

**Comment by onyb** [comment] 2021-04-16 22:22
I think this is a regression due to the recently merged JSON-RPC Batch implementation. cc: @jakesyl

We should try to include a fix in 0.22.0 (#1706) - should be quite simple to implement from the look of it. @jcvernaleo

**Comment by jcvernaleo** [comment] 2021-07-13 14:03
I was under the impression that the rpcversion was supposed to be there.  @jakesyl care to look at this?

**Comment by Sjors** [comment] 2021-08-20 10:45
I'm seeing this error too with 0.22 beta...

**Closed** 2022-04-09 10:56 UTC

**Comment by nikicat** [comment] 2023-06-19 11:54
I still getting this error, but it's easy to fix with this commit https://github.com/nikicat/btcd/commit/eaac8c96f8fb6bf2944a12015f967f0f483b617b
