### ISSUE TITLE
Can't decode block on testnet

### ISSUE THREAD

**Issue by FrozenPrincess** [btcsuite/btcd#962] opened 2017-06-30 22:17 UTC
Steps to reproduce:
```
	hash, err := chainhash.NewHashFromStr("0000000000000e85b4eeead649ef2c9f446c568b1d5272309b64bb4600ba4388")
	if err != nil {
		return nil, err
	}

	block, err := client.rpcClient.GetBlock(hash)
	if err != nil {
		return nil, err
	}
```

Ends up giving:
`*wire.MessageError readScript: transaction input signature script is larger than the max allowed size [count 13581262730879737548, max 33554432]`

The error bubbles up from here: https://github.com/btcsuite/btcd/blob/a6965d493fdfb833b6b3a83c3958ab18968fe24e/wire/msgtx.go#L681

With the entry point here:
https://github.com/btcsuite/btcd/blob/a6965d493fdfb833b6b3a83c3958ab18968fe24e/wire/msgblock.go#L109

**Comment by FrozenPrincess** [comment] 2017-06-30 22:35
Easier to reproduce example:

```
blockHex := "00000020f36cffebd60dffadecde7e0ed560f3f9dbdca5b3ef1046c6c81a000000000000badb7e03f909b1a957a234a7a92f03ac0061b41e430ca0ac3cf31cb2e299862e528e565917921f1a458bbf0507010000000001010000000000000000000000000000000000000000000000000000000000000000ffffffff3c03248d110004528e56590431e6eb010c5b465459cc9e0100000000000a636b706f6f6c182f77656564636f646572206d6f6c69206b656b636f696e2fffffffff022dd25309000000001976a91427f60a3b92e8a92149b18210457cc6bdc14057be88ac0000000000000000266a24aa21a9ed0507bd17ec52a022355cefe8e04e674c791aaac28bb93c71fdc7a2cd04059dfb0120000000000000000000000000000000000000000000000000000000000000000000000000010000000169a39bc00fd2e4d7fe4d3ffd0737d6d6f218e8cc39e9c43571e91330eac24251010000006b483045022100a299d32a02e7b234d33ed772ed0c2cba8026bcfbe88769bebe8506d42e8a6422022062f369d42a868c6a1dbdeb571a8fbfd9049fa3b0986007592d217fc9234f36df012103155e888e65e9304d8139cc34007c86db3adde6d7297cd31f7f7f6fdd42dfb4dcffffffff0200000000000000001e6a1c424152440000000395ebd5de2d9e3561b12c43da515ccfe38656523656fd0b0c000000001976a914064977cb7b4a2e0c9680df0ef696e9e0e296b39988ac000000000100000001644d250cf90661da02833429f62c3185c6c90702d999aff1f347dd857eae010e01000000db00483045022100f7da93817385119759fd258b6c82ccfdc84dcfa1bb393c26882bccfc57f2ba4002202153062639b900555df78d86c6bce6bad5cd4d9325a28f28b316254e69adb4a901483045022100a3f9942273f3c8dc2c8d0af799c039ad4486f5015a63cc2b2b085c0f52f35e000220733d736176b1ee36d72c27ee55b414d0a6cd18ec5e183708023c2cc9afa843950147522102632178d046673c9729d828cfee388e121f497707f810c131e0d3fc0fe0bd66d62103a0951ec7d3a9da9de171617026442fcd30f34d66100fab539853b43f508787d452aeffffffff0240420f000000000017a914590ffca25bf0049095fb980adf6865ab9f13be3987c5ff496d0000000017a9148ce5408cfeaddb7ccb2545ded41ef4781094548487000000000100000001b3470419f2f442ab53f8afad233d8b54711a3b1fddea9ca875d70bc180be8e66010000006a47304402204f9ed058c826fce68f53ac3ab5ea8480f923149d9ab1d38b660e35037b4caaaf02200cec6f8d3da8f04baa03fd2eba30d7cf54f4b1e5927bff93bb3153c1eddd962f0121037e1d9ed3beef3f0b1ef252ea92b1ef1ded48788db399cfa21928268a6c84e553ffffffff02009f2400000000001976a914ec20a005552e33ef7ce2e1d8fd62cbe336da358788acdd037200000000001976a914c3ce0ffc8de3f01744499742b04043b603a7fcb788ac000000000100000001f160d536bde9b23b3b085245528eb51908d1e430f215c37d9428b00a82a4aa81010000006b483045022100d6abd55bcfdb33b2cfcaeb33d629dd7c79cc36081e556e60611f8e42240e17e502201ca2cf688311b35ba96cadf5ef407e920234eb981c73f53be0800d58cdffab7201210350e85fa30c7db4d5cc36e50c6275f296c9b304f2e548f6234ac16dcb7f2b23d1ffffffff0223ba1902000000001976a9142bc596744cdd167aa3a50597f33342ab8eb2445c88aca0252600000000001976a914ec20a005552e33ef7ce2e1d8fd62cbe336da358788ac000000000100000001a46c0a97eb739add449617b563621a95b972933ab67d5b8fd48b47885c1512cf010000006b48304502210098bff4934f2ff9e2aafb4897c661580c9db0c9d59ef4cffd758d40d4256adff002207c47b5600fb47a81c408a412efe88fca8ef6d1c15e9f0186f4201b826410e8b50121034c68a6756f566a932afbbf0d909a789813f15ff242b8e81087331d106a4e928effffffff0260182300000000001976a914ec20a005552e33ef7ce2e1d8fd62cbe336da358788ac7d8a7300000000001976a914d4421a2d3728cb4e5ba858ca30e1cddb850f2b1f88ac00000000010000000160b820ccc51068a4d2c55b2071be759ef2f19bae1638ebe8979929f50a4a179a01000000fc004730440220201b74e9d287525cb17bee8384b14181fd435a30a48056065b2af0512bf6ba160220623072fba582c88d4d5ede9188c3e175472f04e07973807d59f44212002ad5d70147304402206341c1a1681e3f76f7a214acb5ed2625e0002f1e2d626825027cbbd70c4aa34002204cf9cc127c7d958a4f034dddf6a9ae9cbf9ae4fd5957321ae89769d3b7833067014c695221024df5108c43fc2274ed575089d92746eea700e28085454484e95a3ae3c3cb0b642102515f1e30af6a117451bcddb4769da06d57a0093051a4534c64d93806a8647d2c21038a067728a588c4987beff61a8209ec5fb8cf31b7dfaf0b7f9747947701c04fb853aeffffffff0220a107000000000017a91406ab65380deeb68cd736a1e81646e3ee47fed37187539846000000000017a9145c02589ad47b74749f82fb1f342b9051b0d296fc8700000000"

serializedBlock, err := hex.DecodeString(blockHex)
if err != nil {
	return nil, err
}

// Deserialize the block and return it.
var msgBlock wire.MsgBlock
err = msgBlock.Deserialize(bytes.NewReader(serializedBlock))
if err != nil {
	return nil, err
}
```

**Comment by davecgh** [comment] 2017-07-01 07:47
Thanks for the report, but I'm not able to reproduce this on the latest master.  The first one works as expected:

```Go
	hash, err := chainhash.NewHashFromStr("0000000000000e85b4eeead649ef2c9f446c568b1d5272309b64bb4600ba4388")
	if err != nil {
		log.Fatal(err)
	}

	block, err := client.GetBlock(hash)
	if err != nil {
		log.Fatal(err)
	}
	log.Print(spew.Sdump(block))
```

```
(*wire.MsgBlock)(0xc042084100)({
 Header: (wire.BlockHeader) {
  Version: (int32) 536870912,
  PrevBlock: (chainhash.Hash) (len=32 cap=32) 00000000000017e6305cdc58401fea683be7a293be3810023c3f7f53c497bae0,
  MerkleRoot: (chainhash.Hash) (len=32 cap=32) 6b911149c33778b517b7a21972661d3d764c943ed2abd1f1a1861371a56fb56f,
  Timestamp: (time.Time) 2017-06-30 12:14:13 -0500 CDT,
  Bits: (uint32) 438276631,
  Nonce: (uint32) 3576521268
 },
 Transactions: ([]*wire.MsgTx) (len=15 cap=15) {
  (*wire.MsgTx)(0xc042008240)({
   Version: (int32) 1,
   TxIn: ([]*wire.TxIn) (len=1 cap=1) {
    (*wire.TxIn)(0xc04247c000)({
     PreviousOutPoint: (wire.OutPoint) 0000000000000000000000000000000000000000000000000000000000000000:4294967295,
     SignatureScript: ([]uint8) (len=60 cap=60) {
      00000000  03 14 8d 11 00 04 e5 86  56 59 04 75 88 ea 1f 0c  |........VY.u....|
      00000010  5b 46 54 59 cf 56 01 00  00 00 00 00 0a 63 6b 70  |[FTY.V.......ckp|
      00000020  6f 6f 6c 18 2f 77 65 65  64 63 6f 64 65 72 20 6d  |ool./weedcoder m|
      00000030  6f 6c 69 20 6b 65 6b 63  6f 69 6e 2f              |oli kekcoin/|
     },
     Sequence: (uint32) 4294967295
    })
   },
   TxOut: ([]*wire.TxOut) (len=2 cap=2) {
    (*wire.TxOut)(0xc042008280)({
     Value: (int64) 156917934,
     PkScript: ([]uint8) (len=25 cap=25) {
      00000000  76 a9 14 27 f6 0a 3b 92  e8 a9 21 49 b1 82 10 45  |v..'..;...!I...E|
      00000010  7c c6 bd c1 40 57 be 88  ac                       ||...@W...|
     }
    }),
    ....
    (*wire.TxOut)(0xc042008a60)({
     Value: (int64) 0,
     PkScript: ([]uint8) (len=50 cap=50) {
      00000000  6a 30 45 58 4f 4e 55 4d  01 00 e0 1c 03 00 00 00  |j0EXONUM........|
      00000010  00 00 26 d0 26 86 d0 e4  e8 8a af 23 70 8e 92 0b  |..&.&......#p...|
      00000020  d2 89 de 7a a6 5a 3f 3d  e3 8c 04 d7 18 43 87 c0  |...z.Z?=.....C..|
      00000030  ae be                                             |..|
     }
    })
   },
   LockTime: (uint32) 0
  })
 }
})
```

The second one returns an `unexpected EOF` as it should since it's not a validly-encoded block.

**Comment by FrozenPrincess** [comment] 2017-07-01 13:02
On master I can reproduce this on testnet for all segwit blocks (non segwit blocks i think work fine).

I broke the example into two self contained things, along with their output:
Fetching the block: https://gist.github.com/FrozenPrincess/9a4c0f9ab8aec6008bd7efad7223e97c
Parsing the block:  https://gist.github.com/FrozenPrincess/af01142fd0dcfa633c1282480898ab69

--
@davecgh  if you can't reproduce the first part, i can send you the username/password/host of the bitcoin core testnet node that I'm using

**Comment by davecgh** [comment] 2017-07-01 19:48
Alright I see.  It's because because you're getting a segwit-encoded block from Core.  In my case, I requested it from btcd which is using the standard encoding.

This is because the segwit code for btcd has not yet landed (see PR #656) and it appears that Core has updated their `getblock` RPC to return the new encoding.  As a slight aside, it's incredibly frustrating that the RPC isn't versioned and massively breaking changes like this are just introduced without any versioning and/or flags.

Anyways, using your provided segwit-encoded block (in the second gist), it does indeed error due to the new encoding not being understood, while with #656 it works properly:

Current: `readScript: transaction input signature script is larger than the max allowed size [count 13581262730879737548, max 33554432`

With #656:

```message block is:  {{536870912 00000000000017e6305cdc58401fea683be7a293be3810023c3f7f53c497bae0 6b911149c33778b517b7a21972661d3d764c943ed2abd1f1a1861371a56fb56f 2017-06-30 12:14:13 -0500 CDT 438276631 3576521268} [0xc042050180 0xc042050200 0xc042050240 0xc0420502c0 0xc042050340 0xc0420503c0 0xc042050440 0xc0420504c0 0xc042050540 0xc0420505c0 0xc042050640 0xc0420506c0 0xc042050740 0xc0420507c0 0xc042050840]}```

**Comment by davecgh** [comment] 2017-07-01 19:58
I'll go ahead and leave this open until #656 is finalized and merged to master, but it is resolved by either that or by setting the `-rpcserialversion` flag to 0 on Core so it produces blocks with the standard encoding.

**Comment by FrozenPrincess** [comment] 2017-07-01 21:19
Thanks for looking into it and explaining! Do you have a bitcoin address I can tip?

**Comment by davecgh** [comment] 2017-07-01 22:55
No problem.  Thanks for the offer, but no need to tip.

**Closed** 2017-08-14 04:17 UTC
Labels: compatibility, protocol
