### ISSUE TITLE
[btcec] Deterministic signatures according to RFC6979

### ISSUE THREAD

**Issue by oleganza** [btcsuite/btcd#358] opened 2015-03-30 16:26 UTC
Looks like Go's crypto package does not provide [RFC6979](https://tools.ietf.org/html/rfc6979)-compliant ECDSA signatures. I think we should have that in btcd.

Reference implementations:

* [C in Trezor](https://github.com/trezor/trezor-crypto/blob/9fea8f8ab377dc514e40c6fd1f7c89a74c1d8dc6/ecdsa.c#L256)
* [C in libsecp256k1](https://github.com/bitcoin/secp256k1/blob/d5b53aa81816214aa7c9e1095ff6ee1d4c13f9d2/src/hash_impl.h#L205)
* [Objective-C](https://github.com/oleganza/CoreBitcoin/blob/09eff31fad0597c0d4022be76ecf2b497f4ac161/CoreBitcoin/BTCKey.m#L267)
* [Python](https://github.com/warner/python-ecdsa/blob/4461bf3d29453454945b2cd9e666df306e60d81c/ecdsa/rfc6979.py#L54)

**Comment by zmanian** [comment] 2015-03-30 17:11
There is a go implementation that works with the Bitcoin curve here.

https://github.com/codahale/rfc6979

Strongly in favor of having deterministic signatures be the default for btcd

**Comment by zmanian** [comment] 2015-03-30 17:20
Needs some refactoring to match the coding style in btcd.

**Comment by davecgh** [comment] 2015-03-30 17:57
This is a duplicate of btcwallet#146 and I agree this is something we want.

However, I do want to point out though that it's not something btcd itself has to worry about since it doesn't do any signature generation (only verification) and a deterministic signature is a valid signature, so it will verify as expected.  All signing is done by btcwallet, so that is why the issue over there is the valid issue.

All of that said, the deterministic signing will likely need to go into the btcec package which is in this repository so I'll leave this issue open here as well.

Thanks for the reference implementation links.

**Comment by oleganza** [comment] 2015-03-31 15:18
Hey guys, please see the pull request and move discussion there. 

Thanks!

**Closed** 2015-04-02 14:26 UTC
Labels: btcec, enhancement
