### ISSUE TITLE
reject good block ,sync stall

### ISSUE THREAD

**Issue by mostcute** [btcsuite/btcd#2090] opened 2024-01-03 10:51 UTC
```
2024-01-03 10:42:36.983 [INF] SYNC: Rejected block 000000000000000000018e7d1c93aa263cdb5eb2fdcf8e8dd1b3055f93522d93 from 192.161.48.47:8333 (outbound): previous block 00000000000000000001d5030f9564281ba9c4b50e815e1255cd7944db78ddab is known to be invalid                                                                        
2024-01-03 10:42:37.117 [INF] CHAN: Adding orphan block 00000000000000000001f4f15e6aaf40fb7881689fc6c87c47b03d5aa55aa803 with parent 0000000000000000000036606c14008cfcdf00736c753009354d0689c4c3940e                                                                                                                                 
2024-01-03 10:42:37.242 [INF] CHAN: Adding orphan block 000000000000000000000169e0c6f23bef45735953e105e5890648586b9946db with parent 00000000000000000001f4f15e6aaf40fb7881689fc6c87c47b03d5aa55aa803                                                                                                                                 
2024-01-03 10:42:37.344 [INF] CHAN: Adding orphan block 000000000000000000025b9a6a650ea99e4ac8e78760325f9ce1ac6b5c59cb64 with parent 000000000000000000000169e0c6f23bef45735953e105e5890648586b9946db                                                                                                                                 
2024-01-03 10:42:37.683 [INF] CHAN: Adding orphan block 00000000000000000001a0c79151fc0a89810d952c17150f0f01014906df1330 with parent 00000000000000000000109dd0be049221d85fef4a362947364873b0dc25a906                                                                                                                                 
2024-01-03 10:42:37.777 [INF] CHAN: Adding orphan block 000000000000000000005b2dd9080dfdf9b4641d956990403850b5f5330245eb with parent 00000000000000000001a0c79151fc0a89810d952c17150f0f01014906df1330                                                                                                                                 
2024-01-03 10:42:37.883 [INF] CHAN: Adding orphan block 000000000000000000014e43344e90e01492cf85716b8e37b2e2a4ea989a70d5 with parent 000000000000000000005b2dd9080dfdf9b4641d956990403850b5f5330245eb                                                                                                                                 
```

**Comment by mostcute** [comment] 2024-01-03 10:52
code version b1b94202082b8e22160df31349992f37fb360f75

**Comment by mostcute** [comment] 2024-01-04 02:14
i have resync 5 times in last mounth,always lost sync in the last

**Comment by mostcute** [comment] 2024-01-05 09:06
i failed again today 
```
2024-01-05 16:38:43.501 [INF] SYNC: Rejected block 00000000000000000001a9f3b77416e01cea22c0800a11756aec799d5683359a from 60.205.205.119:8333 (outbound): output 7c006995f51e1ebc72f7a3ae5e14c50f88c99de9bfb43c2602d39ad32e86389e:0 referenced from transaction e3dcc797b912dd204d1753a202401a1c7cdddab4a99bca3cbeb38223171d8937:2 either does not exist or has already been spent
```

i think there might have data lost in utxo cache

**Comment by r1ky** [comment] 2024-02-10 19:07
Ah. This appears to be what I'm seeing as well. Both on v0.23.3 and v0.24.0. Repeating from my question in Github Discussion Q&A below.

I have just started running btcsuite/btcd v0.24.0. After spending a couple days initializing the blockchain it no longer appears to be writing new blocks. btcctl getblockcount continually reports 829813 which is currently about 2 hours behind the block count reported on Blockexplorer.

The data files reflect this issue with nothing being written for the past ~2h:

```
root@meta-01:~# ls -lt /data/btcd-data/data/mainnet/blocks_ffldb/ | head
total 535368128
drwxr-xr-x 2 root root   1859584 Feb 10 16:58 metadata
-rw-r--r-- 1 root root 162222618 Feb 10 14:53 000001022.fdb
-rw-r--r-- 1 root root 536286030 Feb 10 14:51 000001021.fdb
-rw-r--r-- 1 root root 535253677 Feb 10 14:47 000001020.fdb
```

I've included a snippet from the logs below that appears to be the start of the problem. After that there are just repeated occurrences of the last reported Rejected block reported at the end of the log excerpt.

```
2024-02-10 14:53:50.935 [INF] SYNC: Rejected block 00000000000000000001a9931d3181dcad10319187e0b668fc2db0f8dff656c9 from 158.69.116.1
69:8333 (outbound): output 314f9abdebc73c4c2062b2416278f4956b399f4f2ae1250aa065e23fab85e9fd:0 referenced from transaction 1dc8c6b6063
3eb711818a95c23034faf0fffdb278ac29476b99bfd47c029a209:49 either does not exist or has already been spent
2024-02-10 14:53:50.968 [INF] SYNC: Rejected block 00000000000000000003b3480ed47cd0d435069efcc1eccdbcd84629a9e912ae from 158.69.116.1
69:8333 (outbound): previous block 00000000000000000001a9931d3181dcad10319187e0b668fc2db0f8dff656c9 is known to be invalid
2024-02-10 14:53:51.019 [INF] CHAN: Adding orphan block 00000000000000000001be54eb192b683a066b035ec59547de17eaaded2cfa73 with parent 
00000000000000000003b3480ed47cd0d435069efcc1eccdbcd84629a9e912ae
2024-02-10 14:53:51.044 [INF] CHAN: Adding orphan block 00000000000000000000444b5117d4dd006490de38ce067443ac1c9a1ccc0f08 with parent 
00000000000000000001be54eb192b683a066b035ec59547de17eaaded2cfa73
2024-02-10 14:53:51.109 [INF] CHAN: Adding orphan block 00000000000000000001a05e045444fb4227933d5be5f0efc54ca926963d0c43 with parent 
00000000000000000000444b5117d4dd006490de38ce067443ac1c9a1ccc0f08
2024-02-10 14:53:51.206 [INF] CHAN: Adding orphan block 000000000000000000019e6204beb96b122036247a8664bf4d66a8b811f769db with parent 
00000000000000000001a05e045444fb4227933d5be5f0efc54ca926963d0c43
2024-02-10 14:53:51.253 [INF] CHAN: Adding orphan block 00000000000000000000b7f267dd8f7a867287fb0c07e164187cf585c5639d02 with parent 
000000000000000000019e6204beb96b122036247a8664bf4d66a8b811f769db
2024-02-10 14:53:51.305 [INF] CHAN: Adding orphan block 0000000000000000000227e6c2da74b6ef93fc7743a5878fc6e07c8b7f887ee4 with parent 00000000000000000000b7f267dd8f7a867287fb0c07e164187cf585c5639d02
2024-02-10 14:53:51.377 [INF] CHAN: Adding orphan block 00000000000000000003237d04ad2415292d0fe61e5d367b72fd07b3172e1199 with parent 0000000000000000000227e6c2da74b6ef93fc7743a5878fc6e07c8b7f887ee4
2024-02-10 14:53:51.436 [INF] CHAN: Adding orphan block 00000000000000000000c6cd552536b518f42a959a0576c19fad4421ae858ed2 with parent 00000000000000000003237d04ad2415292d0fe61e5d367b72fd07b3172e1199
2024-02-10 14:53:51.493 [INF] CHAN: Adding orphan block 00000000000000000001c720d7375d41a0839da2e8209d270e68794df61b65a1 with parent 00000000000000000000c6cd552536b518f42a959a0576c19fad4421ae858ed2
2024-02-10 14:53:51.544 [INF] CHAN: Adding orphan block 00000000000000000002db1605171cc371564792013fcb1898bbce8a4fa5d5e2 with parent 00000000000000000001c720d7375d41a0839da2e8209d270e68794df61b65a1
2024-02-10 14:53:51.585 [INF] CHAN: Adding orphan block 0000000000000000000380f62b7ee0b43ebd0e2e3389fdcd782ebd5b3fcb0513 with parent 00000000000000000002db1605171cc371564792013fcb1898bbce8a4fa5d5e2
2024-02-10 14:53:51.636 [INF] CHAN: Adding orphan block 00000000000000000003775d97ec610e54b8b201b5feff6db72ff9d7754beac2 with parent 0000000000000000000380f62b7ee0b43ebd0e2e3389fdcd782ebd5b3fcb0513
2024-02-10 14:53:51.676 [INF] CHAN: Adding orphan block 000000000000000000001b770eb2d1a54be1b5a1b5270921b361bc72b59591e2 with parent 00000000000000000003775d97ec610e54b8b201b5feff6db72ff9d7754beac2
2024-02-10 14:53:51.757 [INF] CHAN: Adding orphan block 00000000000000000003a3b72ea88be42356514ebd74a7c2a80a539a71befd42 with parent 000000000000000000001b770eb2d1a54be1b5a1b5270921b361bc72b59591e2
2024-02-10 14:53:51.805 [INF] CHAN: Adding orphan block 000000000000000000001d009527deada865fbf9751609d7419aa8564f0b1eb9 with parent 00000000000000000003a3b72ea88be42356514ebd74a7c2a80a539a71befd42
2024-02-10 14:53:51.867 [INF] CHAN: Adding orphan block 000000000000000000031895d8101046803363852d84c9fcf3c10c18baa06978 with parent 000000000000000000001d009527deada865fbf9751609d7419aa8564f0b1eb9
2024-02-10 14:53:51.933 [INF] CHAN: Adding orphan block 00000000000000000000956e8b14383d75dc47aa86b7c745e8074ffd801f88af with parent 000000000000000000031895d8101046803363852d84c9fcf3c10c18baa06978
2024-02-10 14:53:52.005 [INF] CHAN: Adding orphan block 00000000000000000002237a1aa31b928a7f89211c9e82c9e539405eb7f6d224 with parent 00000000000000000000956e8b14383d75dc47aa86b7c745e8074ffd801f88af
2024-02-10 14:53:52.575 [INF] SYNC: Rejected block 00000000000000000003b3480ed47cd0d435069efcc1eccdbcd84629a9e912ae from 158.69.116.169:8333 (outbound): previous block 00000000000000000001a9931d3181dcad10319187e0b668fc2db0f8dff656c9 is known to be invalid
```

**Comment by kcalvinalvin** [comment] 2024-02-16 13:54
> ```
> 
> 2024-01-03 10:42:36.983 [INF] SYNC: Rejected block 000000000000000000018e7d1c93aa263cdb5eb2fdcf8e8dd1b3055f93522d93 from 192.161.48.47:8333 (outbound): previous block 00000000000000000001d5030f9564281ba9c4b50e815e1255cd7944db78ddab is known to be invalid                                                                        
> 
> 2024-01-03 10:42:37.117 [INF] CHAN: Adding orphan block 00000000000000000001f4f15e6aaf40fb7881689fc6c87c47b03d5aa55aa803 with parent 0000000000000000000036606c14008cfcdf00736c753009354d0689c4c3940e                                                                                                                                 
> 
> 2024-01-03 10:42:37.242 [INF] CHAN: Adding orphan block 000000000000000000000169e0c6f23bef45735953e105e5890648586b9946db with parent 00000000000000000001f4f15e6aaf40fb7881689fc6c87c47b03d5aa55aa803                                                                                                                                 
> 
> 2024-01-03 10:42:37.344 [INF] CHAN: Adding orphan block 000000000000000000025b9a6a650ea99e4ac8e78760325f9ce1ac6b5c59cb64 with parent 000000000000000000000169e0c6f23bef45735953e105e5890648586b9946db                                                                                                                                 
> 
> 2024-01-03 10:42:37.683 [INF] CHAN: Adding orphan block 00000000000000000001a0c79151fc0a89810d952c17150f0f01014906df1330 with parent 00000000000000000000109dd0be049221d85fef4a362947364873b0dc25a906                                                                                                                                 
> 
> 2024-01-03 10:42:37.777 [INF] CHAN: Adding orphan block 000000000000000000005b2dd9080dfdf9b4641d956990403850b5f5330245eb with parent 00000000000000000001a0c79151fc0a89810d952c17150f0f01014906df1330                                                                                                                                 
> 
> 2024-01-03 10:42:37.883 [INF] CHAN: Adding orphan block 000000000000000000014e43344e90e01492cf85716b8e37b2e2a4ea989a70d5 with parent 000000000000000000005b2dd9080dfdf9b4641d956990403850b5f5330245eb                                                                                                                                 
> 
> ```

What's config you're using for the node here?

**Comment by kcalvinalvin** [comment] 2024-02-16 13:57
> Ah. This appears to be what I'm seeing as well. Both on v0.23.3 and v0.24.0. Repeating from my question in Github Discussion Q&A below.
> 
> 
> 
> I have just started running btcsuite/btcd v0.24.0. After spending a couple days initializing the blockchain it no longer appears to be writing new blocks. btcctl getblockcount continually reports 829813 which is currently about 2 hours behind the block count reported on Blockexplorer.
> 
> 
> 
> The data files reflect this issue with nothing being written for the past ~2h:
> 
> 
> 
> ```
> 
> root@meta-01:~# ls -lt /data/btcd-data/data/mainnet/blocks_ffldb/ | head
> 
> total 535368128
> 
> drwxr-xr-x 2 root root   1859584 Feb 10 16:58 metadata
> 
> -rw-r--r-- 1 root root 162222618 Feb 10 14:53 000001022.fdb
> 
> -rw-r--r-- 1 root root 536286030 Feb 10 14:51 000001021.fdb
> 
> -rw-r--r-- 1 root root 535253677 Feb 10 14:47 000001020.fdb
> 
> ```
> 
> 
> 
> I've included a snippet from the logs below that appears to be the start of the problem. After that there are just repeated occurrences of the last reported Rejected block reported at the end of the log excerpt.
> 
> 
> 
> ```
> 
> 2024-02-10 14:53:50.935 [INF] SYNC: Rejected block 00000000000000000001a9931d3181dcad10319187e0b668fc2db0f8dff656c9 from 158.69.116.1
> 
> 69:8333 (outbound): output 314f9abdebc73c4c2062b2416278f4956b399f4f2ae1250aa065e23fab85e9fd:0 referenced from transaction 1dc8c6b6063
> 
> 3eb711818a95c23034faf0fffdb278ac29476b99bfd47c029a209:49 either does not exist or has already been spent
> 
> 2024-02-10 14:53:50.968 [INF] SYNC: Rejected block 00000000000000000003b3480ed47cd0d435069efcc1eccdbcd84629a9e912ae from 158.69.116.1
> 
> 69:8333 (outbound): previous block 00000000000000000001a9931d3181dcad10319187e0b668fc2db0f8dff656c9 is known to be invalid
> 
> 2024-02-10 14:53:51.019 [INF] CHAN: Adding orphan block 00000000000000000001be54eb192b683a066b035ec59547de17eaaded2cfa73 with parent 
> 
> 00000000000000000003b3480ed47cd0d435069efcc1eccdbcd84629a9e912ae
> 
> 2024-02-10 14:53:51.044 [INF] CHAN: Adding orphan block 00000000000000000000444b5117d4dd006490de38ce067443ac1c9a1ccc0f08 with parent 
> 
> 00000000000000000001be54eb192b683a066b035ec59547de17eaaded2cfa73
> 
> 2024-02-10 14:53:51.109 [INF] CHAN: Adding orphan block 00000000000000000001a05e045444fb4227933d5be5f0efc54ca926963d0c43 with parent 
> 
> 00000000000000000000444b5117d4dd006490de38ce067443ac1c9a1ccc0f08
> 
> 2024-02-10 14:53:51.206 [INF] CHAN: Adding orphan block 000000000000000000019e6204beb96b122036247a8664bf4d66a8b811f769db with parent 
> 
> 00000000000000000001a05e045444fb4227933d5be5f0efc54ca926963d0c43
> 
> 2024-02-10 14:53:51.253 [INF] CHAN: Adding orphan block 00000000000000000000b7f267dd8f7a867287fb0c07e164187cf585c5639d02 with parent 
> 
> 000000000000000000019e6204beb96b122036247a8664bf4d66a8b811f769db
> 
> 2024-02-10 14:53:51.305 [INF] CHAN: Adding orphan block 0000000000000000000227e6c2da74b6ef93fc7743a5878fc6e07c8b7f887ee4 with parent 00000000000000000000b7f267dd8f7a867287fb0c07e164187cf585c5639d02
> 
> 2024-02-10 14:53:51.377 [INF] CHAN: Adding orphan block 00000000000000000003237d04ad2415292d0fe61e5d367b72fd07b3172e1199 with parent 0000000000000000000227e6c2da74b6ef93fc7743a5878fc6e07c8b7f887ee4
> 
> 2024-02-10 14:53:51.436 [INF] CHAN: Adding orphan block 00000000000000000000c6cd552536b518f42a959a0576c19fad4421ae858ed2 with parent 00000000000000000003237d04ad2415292d0fe61e5d367b72fd07b3172e1199
> 
> 2024-02-10 14:53:51.493 [INF] CHAN: Adding orphan block 00000000000000000001c720d7375d41a0839da2e8209d270e68794df61b65a1 with parent 00000000000000000000c6cd552536b518f42a959a0576c19fad4421ae858ed2
> 
> 2024-02-10 14:53:51.544 [INF] CHAN: Adding orphan block 00000000000000000002db1605171cc371564792013fcb1898bbce8a4fa5d5e2 with parent 00000000000000000001c720d7375d41a0839da2e8209d270e68794df61b65a1
> 
> 2024-02-10 14:53:51.585 [INF] CHAN: Adding orphan block 0000000000000000000380f62b7ee0b43ebd0e2e3389fdcd782ebd5b3fcb0513 with parent 00000000000000000002db1605171cc371564792013fcb1898bbce8a4fa5d5e2
> 
> 2024-02-10 14:53:51.636 [INF] CHAN: Adding orphan block 00000000000000000003775d97ec610e54b8b201b5feff6db72ff9d7754beac2 with parent 0000000000000000000380f62b7ee0b43ebd0e2e3389fdcd782ebd5b3fcb0513
> 
> 2024-02-10 14:53:51.676 [INF] CHAN: Adding orphan block 000000000000000000001b770eb2d1a54be1b5a1b5270921b361bc72b59591e2 with parent 00000000000000000003775d97ec610e54b8b201b5feff6db72ff9d7754beac2
> 
> 2024-02-10 14:53:51.757 [INF] CHAN: Adding orphan block 00000000000000000003a3b72ea88be42356514ebd74a7c2a80a539a71befd42 with parent 000000000000000000001b770eb2d1a54be1b5a1b5270921b361bc72b59591e2
> 
> 2024-02-10 14:53:51.805 [INF] CHAN: Adding orphan block 000000000000000000001d009527deada865fbf9751609d7419aa8564f0b1eb9 with parent 00000000000000000003a3b72ea88be42356514ebd74a7c2a80a539a71befd42
> 
> 2024-02-10 14:53:51.867 [INF] CHAN: Adding orphan block 000000000000000000031895d8101046803363852d84c9fcf3c10c18baa06978 with parent 000000000000000000001d009527deada865fbf9751609d7419aa8564f0b1eb9
> 
> 2024-02-10 14:53:51.933 [INF] CHAN: Adding orphan block 00000000000000000000956e8b14383d75dc47aa86b7c745e8074ffd801f88af with parent 000000000000000000031895d8101046803363852d84c9fcf3c10c18baa06978
> 
> 2024-02-10 14:53:52.005 [INF] CHAN: Adding orphan block 00000000000000000002237a1aa31b928a7f89211c9e82c9e539405eb7f6d224 with parent 00000000000000000000956e8b14383d75dc47aa86b7c745e8074ffd801f88af
> 
> 2024-02-10 14:53:52.575 [INF] SYNC: Rejected block 00000000000000000003b3480ed47cd0d435069efcc1eccdbcd84629a9e912ae from 158.69.116.169:8333 (outbound): previous block 00000000000000000001a9931d3181dcad10319187e0b668fc2db0f8dff656c9 is known to be invalid
> 
> ```

Could you post your config and the full logs here? Thanks for your help :)

**Comment by r1ky** [comment] 2024-02-16 16:32
Hey @kcalvinalvin - my config (from systemd), such as it is:

```
/usr/bin/docker run --rm --name %n -e RPCPASS=fNR*REDACTED*dKF \
-p 8333:8333 -v /data/btcd:/root/.btcd metalogic/btcd:0.24.0 \
--rpcuser=rpc --rpcpass=fNR*REDACTED*dKF```

The referenced Docker image was built using the Dockerfile from the distribution.

As for logs, I'm afraid they are no longer available (I switched to Bitcoin core and due to disk space issues cleared BTCD).

If you think you have a fix (eg #2121) I can give it a try and follow up here.

**Comment by kcalvinalvin** [comment] 2024-02-26 15:40
> Hey @kcalvinalvin - my config (from systemd), such as it is:
> 
> ```
> /usr/bin/docker run --rm --name %n -e RPCPASS=fNR*REDACTED*dKF \
> -p 8333:8333 -v /data/btcd:/root/.btcd metalogic/btcd:0.24.0 \
> --rpcuser=rpc --rpcpass=fNR*REDACTED*dKF```
> 
> The referenced Docker image was built using the Dockerfile from the distribution.
> 
> As for logs, I'm afraid they are no longer available (I switched to Bitcoin core and due to disk space issues cleared BTCD).
> 
> If you think you have a fix (eg #2121) I can give it a try and follow up here.
> ```

Yes that PR should fix the bug that you were noticing.

**Comment by kcalvinalvin** [comment] 2024-02-26 16:07
> @kcalvinalvin - I tried your branch 2024-02-15-dont-rely-on-height-fetching. Did the IBD from scratch but am experiencing the same result. IBD completes and then almost immediately start seeing similar to above:
> 
> ```
> 2024-02-10 14:53:50.935 [INF] SYNC: Rejected block 00000000000000000001a9931d3181dcad10319187e0b668fc2db0f8dff656c9 from 158.69.116.1
> 
> 69:8333 (outbound): output 314f9abdebc73c4c2062b2416278f4956b399f4f2ae1250aa065e23fab85e9fd:0 referenced from transaction 1dc8c6b6063
> 
> 3eb711818a95c23034faf0fffdb278ac29476b99bfd47c029a209:49 either does not exist or has already been spent
> 
> 2024-02-10 14:53:50.968 [INF] SYNC: Rejected block 00000000000000000003b3480ed47cd0d435069efcc1eccdbcd84629a9e912ae from 158.69.116.1
> ```

Could you post your full logs and the config?

There's a btcd node with the PR applied on https://forkmonitor.info/ that is able to sync up to the tip and I verified this locally.

**Comment by r1ky** [comment] 2024-02-26 16:09
@kcalvinalvin - by full logs you mean including everything from the beginning of time?

**Comment by kcalvinalvin** [comment] 2024-02-26 16:11
> @kcalvinalvin - by full logs you mean including everything from the beginning of time?

At least from when you started up the node for the full resync this time around. But more the merrier :)

**Comment by r1ky** [comment] 2024-02-28 16:28
Hi @kcalvinalvin - the complete logs from IBD are here:

https://metalogicsoftware.ca/downloads/btcd.log

There is no config file. All config is passed on the command line inside Docker:

```
...
ExecStartPre=/usr/bin/docker pull metalogic/btcd:2122
ExecStart=/usr/bin/docker run --rm --name %n -e RPCPASS=fNR**REDACTED**dKF -p 8333:8333 -v /data/btcd:/root/.btcd metalogic/btcd:2122 --rpcuser=rpc --rpcpass=fNR**REDACTED**rdKF
...
```

**Comment by kcalvinalvin** [comment] 2024-03-03 09:22
> Hi @kcalvinalvin - the complete logs from IBD are here:
> 
> https://metalogicsoftware.ca/downloads/btcd.log
> 
> There is no config file. All config is passed on the command line inside Docker:
> 
> ```
> ...
> ExecStartPre=/usr/bin/docker pull metalogic/btcd:2122
> ExecStart=/usr/bin/docker run --rm --name %n -e RPCPASS=fNR**REDACTED**dKF -p 8333:8333 -v /data/btcd:/root/.btcd metalogic/btcd:2122 --rpcuser=rpc --rpcpass=fNR**REDACTED**rdKF
> ...
> ```

Hey. I was able to reproduce your bug. Working towards a fix

**Comment by kcalvinalvin** [comment] 2024-03-15 08:28
Hey @r1ky. Could you try syncing now with master?

**Comment by r1ky** [comment] 2024-03-15 16:18
Will try to get to it this weekend @kcalvinalvin. Thanks!

**Comment by r1ky** [comment] 2024-03-16 23:01
Hey @kcalvinalvin - just confirming. You mean btcsuite/btcd master, right? Not the master for your fork?

**Comment by kcalvinalvin** [comment] 2024-03-18 08:00
> Hey @kcalvinalvin - just confirming. You mean btcsuite/btcd master, right? Not the master for your fork?

Yes the current master on btcsuite/btcd

**Comment by r1ky** [comment] 2024-03-18 19:17
Thanks @kcalvinalvin. The latest build of master is now correctly tracking with the latest block report on blockexplorer.one. I'll keep an eye on it for the next few days, but so far it's looking good!

**Comment by kcalvinalvin** [comment] 2024-03-26 04:11
Closing since I'm no longer able to reproduce the bug with the latest tag

**Closed by kcalvinalvin** 2024-03-26 04:11 UTC
