### ISSUE TITLE
stuck on blockcount 286717

### ISSUE THREAD

**Issue by vmatekole** [btcsuite/btcd#244] opened 2015-01-17 14:05 UTC
Deployed btcd in "nolisten" mode to a server running bitcoind. Blockcount is stuck on 286717. Although,  Debug log reports receiving more recent blocks from other peers:

Received inv (block 000000000000000031b9a9358db8c41a46ac35ffaa3ccd43cf925ff7a9b0a646) from 93.103.156.226:8333 (outbound)
Jan 17 14:57:51 subversive btcd.log: 08:57:51 2015-01-17 [DBG] PEER: Received inv (block 00000000000000002f4ddafbd56a93a69cb2a3a08b657ee57fd8e341f45d729e) from 93.103.156.226:8333 (outbound)
Jan 17 14:57:51 subversive btcd.log: 08:57:51 2015-01-17 [DBG] PEER: Received inv (block 00000000000000002219dd5bcb6eebc941fdb970c81577b1ccc7d2db985e6384) from 93.103.156.226:8333 (outbound)
Jan 17 14:57:56 subversive btcd.log: 08:57:56 2015-01-17 [DBG] PEER: Received inv (block 000000000000000008f33c87d1cbe000f7e91721b5c91f4f9ae73ad3df561c5c) from 93.103.156.226:8333 (outbound)
Jan 17 14:58:10 subversive btcd.log: 08:58:10 2015-01-17 [DBG] PEER: Received inv (block 000000000000000029ef0a97c9317ba56a167ffbce90c54f9ce0121f558bc052) from 93.103.156.226:8333 (outbound)
Jan 17 14:58:11 subversive btcd.log: 08:58:11 2015-01-17 [DBG] PEER: Received inv (block 000000000000000016c9ca511ad8373cdb711cbb12a671aac701a9a9d3d68caa) from 93.103.156.226:8333 (outbound)

**Comment by davecgh** [comment] 2015-01-17 17:23
Thanks for the report.  This is a duplicate of #231.

**Comment by davecgh** [comment] 2015-01-30 19:12
This was fixed by #262.

**Closed by davecgh** 2015-01-30 19:12 UTC
