### ISSUE TITLE
Exeption in code

### ISSUE THREAD

**Issue by stremovsky** [btcsuite/btcd#1214] opened 2018-07-10 13:36 UTC
Hello

Please advise what to do.

I am getting the same error all the time now.

2018-07-10 13:35:01.452 [INF] SYNC: New valid peer 174.138.35.229:8333 (outbound) (/Satoshi:0.16.1/)
2018-07-10 13:35:01.503 [INF] SYNC: New valid peer 18.191.59.127:8333 (outbound) (/Satoshi:0.12.1(bitcore)/)
2018-07-10 13:35:01.879 [INF] CHAN: REORGANIZE: Block 00000000000000000519465b791624015d6993e08bc6621b4265294368f14463 is causing a reorganize.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x75a887]

goroutine 76 [running]:
github.com/btcsuite/btcd/blockchain.(*BlockChain).reorganizeChain(0xc4207ea180, 0xc425a0c300, 0xc425a0c2a0, 0xc42009ce20, 0x1)
        /data/go/src/github.com/btcsuite/btcd/blockchain/chain.go:1009 +0x12c7
github.com/btcsuite/btcd/blockchain.(*BlockChain).connectBestChain(0xc4207ea180, 0xc429098150, 0xc4256ac5b0, 0x0, 0x0, 0x0, 0xc42a719ad8)
        /data/go/src/github.com/btcsuite/btcd/blockchain/chain.go:1129 +0xa5f
github.com/btcsuite/btcd/blockchain.(*BlockChain).maybeAcceptBlock(0xc4207ea180, 0xc4256ac5b0, 0xffffffff00000000, 0x0, 0x0, 0xec07c0)
        /data/go/src/github.com/btcsuite/btcd/blockchain/accept.go:79 +0x207
github.com/btcsuite/btcd/blockchain.(*BlockChain).ProcessBlock(0xc4207ea180, 0xc4256ac5b0, 0xc400000000, 0xc42b6c0000, 0x0, 0x0)
        /data/go/src/github.com/btcsuite/btcd/blockchain/process.go:228 +0x2b5
github.com/btcsuite/btcd/netsync.(*SyncManager).handleBlockMsg(0xc4201ca370, 0xc429076a80)
        /data/go/src/github.com/btcsuite/btcd/netsync/manager.go:569 +0x205
github.com/btcsuite/btcd/netsync.(*SyncManager).blockHandler(0xc4201ca370)
        /data/go/src/github.com/btcsuite/btcd/netsync/manager.go:1166 +0x548
created by github.com/btcsuite/btcd/netsync.(*SyncManager).Start
        /data/go/src/github.com/btcsuite/btcd/netsync/manager.go:1388 +0xe3

**Comment by davecgh** [comment] 2018-07-12 00:51
This is a duplicate of #1194 and is resolved by #1215.

**Closed** 2018-07-18 03:36 UTC
