### ISSUE TITLE
is there anyway to speedup the IBD and sync of btcd?

### ISSUE THREAD

**Issue by souvikhaldar** [btcsuite/btcd#2056] opened 2023-11-06 17:04 UTC
I have very powerful system but btcd uses very low ram and cpu!

**Comment by saubyk** [comment] 2023-11-06 17:33
There are a few prs in progress to address IBD e.g.:
https://github.com/btcsuite/btcd/pull/1955
https://github.com/btcsuite/btcd/pull/1978

cc: @kcalvinalvin 

And some additional work planned to parallelize block downloads from multiple peers to speed up the sync. You should be able to observe significant improvements after these prs are merged

**Comment by Roasbeef** [comment] 2023-11-06 18:11
Closing as a duplicate of https://github.com/btcsuite/btcd/issues/1339

**Closed by Roasbeef** 2023-11-06 18:11 UTC
