### ISSUE TITLE
Broken by block 802145

### ISSUE THREAD

**Issue by shocknet-justin** [btcsuite/btcd#2147] opened 2024-03-28 17:31 UTC
[INF] SYNC: Rejected block 00000000000000000002b6a3bd3d84beb7947a6e73237caba184c25637f3f545 previous block 0000000000000000000114b4228a18d1b914957d2d5dcbc1f1f04209fb325579 is known to be invalid

I just noticed this on a system thats been passively running 23.3, found it was just adding orphans... I updated it to 24 but no joy

Do I need to nuke and start it fresh?

**Comment by Roasbeef** [comment] 2024-03-28 18:03
Duplicate of https://github.com/btcsuite/btcd/issues/2121 ? 

23.3 had an issue related to an erroneous Dos parsing limit. 

The latest version to be released is v0.24.2: https://github.com/btcsuite/btcd/pull/2136 

This fixes a bug introduced with the new UTXO set cache.

**Comment by shocknet-justin** [comment] 2024-03-28 18:08
This node has never been pruned so I don't think its related, also quite a bit earlier in blockheight

**Comment by shocknet-justin** [comment] 2024-03-28 18:11
Just upgraded to 24.2 and it still starts at this same invalid block

**Comment by Roasbeef** [comment] 2024-03-28 21:17
Yeh we don't have `reconsiderblock` yet (that block is marked in the db as one it rejected, so it won't auto reconsider), but we aim to add it in an upcoming PR. Till then you'll need to re-sync unfortunately. Also see: https://github.com/btcsuite/btcd/issues/2090 

Do you have even earlier logs re when the instance first occurred?

**Comment by shocknet-justin** [comment] 2024-03-28 23:51
No problem

Looked for logs but a 1GB dump only went back about a week, full of "Adding orphan block"

**Comment by Roasbeef** [comment] 2024-06-27 23:47
With #2154 merged, you should be able to use `reconsiderblock` to resolve the issue if you havne't already. In `v0.24.2` we fixed a number of bugs related to interactions w/ re-orgs, the utxo cache, and pruning. As mentioend above `v0.23.3` has a known issue related to an erroneous DoS parsing limit, so I recommend you update to `v0.24.2`.

**Closed by Roasbeef** 2024-06-27 23:47 UTC
