### ISSUE TITLE
Zero Confirmation Transactions limit

### ISSUE THREAD

**Issue by arvin-lau** [btcsuite/btcd#2246] opened 2024-09-02 09:07 UTC
What is the btcd zero confirmation transaction limit? Is it 25?

**Comment by guggero** [comment] 2024-09-02 09:15
Duplicate of https://github.com/btcsuite/btcd/discussions/2247.

**Closed by guggero** 2024-09-02 09:15 UTC

**Comment by arvin-lau** [comment] 2024-09-02 09:32
> Duplicate of #2247.

Can you answer that question?
